name: '.infra-rg-networking-tewheke-orchestration-workflow'

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'The environment to deploy (e.g., dev, test, prod)'
        required: true
        type: string

jobs:
  deploy_resource_group:
    permissions:
      id-token: write # Required for OIDC authentication
      contents: read  # To access repository files if needed
    uses: ./.github/workflows/infra-rg-networking-tewheke.yaml
    with:
      environment: ${{ github.event.inputs.environment }}
    secrets: inherit

  deploy_nsgs:
    permissions:
      id-token: write # Required for OIDC authentication
      contents: read  # To access repository files if needed
    uses: ./.github/workflows/infra-nsgs-tewheke-workflow.yaml
    with:
      environment: ${{ github.event.inputs.environment }}
    needs: deploy_resource_group  # Ensures this job runs after deploy_resource_group
    secrets: inherit

  deploy_vnet:
    permissions:
      id-token: write # Required for OIDC authentication
      contents: read  # To access repository files if needed
    uses: ./.github/workflows/infra-vnet-tewheke-workflow.yaml
    with:
      environment: ${{ github.event.inputs.environment }}
    needs: deploy_nsgs  # Ensures this job runs after deploy_nsgs
    secrets: inherit

  deploy_dns_zone:
    permissions:
      id-token: write # Required for OIDC authentication
      contents: read  # To access repository files if needed
    uses: ./.github/workflows/infra-privatednszones-tewheke-workflow.yaml
    with:
      environment: ${{ github.event.inputs.environment }}
    needs: deploy_vnet  # Ensures this job runs after deploy_vnet
    secrets: inherit

  # deploy_app_gateway:
  #   permissions:
  #     id-token: write # Required for OIDC authentication
  #     contents: read  # To access repository files if needed
  #   uses: ./.github/workflows/infra-appgw-tewheke-workflow.yaml
  #   with:
  #     environment: ${{ github.event.inputs.environment }}
  #   needs: deploy_dns_zone  # Ensures this job runs after deploy_dns_zone
  #   secrets: inherit