name: '.rg-networking-tewheke-orchestration-workflow'

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'The environment to deploy (e.g., dev, test, prod)'
        required: true
        type: string

jobs:
  deploy_resource_group:
    permissions:
      id-token: write # Required for OIDC authentication
      contents: read  # To access repository files if needed
    uses: ./.github/workflows/rg-networking-tewheke.yaml
    with:
      environment: ${{ github.event.inputs.environment }}
      root_directory: 'rg-networking-tewheke/Infrastructure'
      sub_directory: 'rg-networking-tewheke/Infrastructure/ResourceGroup'
      terraform_state_filename: 'rg-networking-tewheke.tfstate'
    secrets: inherit

  deploy_nsgs:
    permissions:
      id-token: write # Required for OIDC authentication
      contents: read  # To access repository files if needed
    uses: ./.github/workflows/nsgs-tewheke-workflow.yaml
    with:
      environment: ${{ github.event.inputs.environment }}
      root_directory: 'rg-networking-tewheke/Infrastructure'
      sub_directory: 'rg-networking-tewheke/Infrastructure/NetworkSecurityGroup'
      terraform_state_filename: 'rg-networking-tewheke.tfstate'
    needs: deploy_resource_group  # Ensures this job runs after deploy_resource_group
    secrets: inherit

  deploy_vnet:
    permissions:
      id-token: write # Required for OIDC authentication
      contents: read  # To access repository files if needed
    uses: ./.github/workflows/vnet-tewheke-workflow.yaml
    with:
      environment: ${{ github.event.inputs.environment }}
      root_directory: 'rg-networking-tewheke/Infrastructure'
      sub_directory: 'rg-networking-tewheke/Infrastructure/VirtualNetwork'
      terraform_state_filename: 'rg-networking-tewheke.tfstate'
    needs: deploy_nsgs  # Ensures this job runs after deploy_nsgs
    secrets: inherit

  deploy_dns_zone:
    permissions:
      id-token: write # Required for OIDC authentication
      contents: read  # To access repository files if needed
    uses: ./.github/workflows/privatednszones-tewheke-workflow.yaml
    with:
      environment: ${{ github.event.inputs.environment }}
      root_directory: 'rg-networking-tewheke/Infrastructure'
      sub_directory: 'rg-networking-tewheke/Infrastructure/PrivateDNSZone'
      terraform_state_filename: 'rg-networking-tewheke.tfstate'
    needs: deploy_vnet  # Ensures this job runs after deploy_vnet
    secrets: inherit

  # deploy_app_gateway:
  #   permissions:
  #     id-token: write # Required for OIDC authentication
  #     contents: read  # To access repository files if needed
  #   uses: ./.github/workflows/appgw-tewheke-workflow.yaml
  #   with:
  #     environment: ${{ github.event.inputs.environment }}
  #     root_directory: 'rg-networking-tewheke/Infrastructure'
  #     sub_directory: 'rg-networking-tewheke/Infrastructure/ApplicationGateway'
  #     terraform_state_filename: 'rg-networking-tewheke.tfstate'
  #   needs: deploy_dns_zone  # Ensures this job runs after deploy_dns_zone
  #   secrets: inherit