name: '.rg-networking-tewheke-orchestration-workflow'

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'The environment to deploy (e.g., dev, test, prod)'
        required: true
        type: string

jobs:
  orchestrate:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger RG Networking Workflow
        uses: ./.github/workflows/rg-networking-tewheke.yaml
        with:
          environment: ${{ github.event.inputs.environment }}

      - name: Trigger NSG Workflow
        uses: ./.github/workflows/nsgs-tewheke-workflow.yaml
        with:
          environment: ${{ github.event.inputs.environment }}

      - name: Trigger VNET Workflow
        uses: ./.github/workflows/vnet-tewheke-workflow.yaml
        with:
          environment: ${{ github.event.inputs.environment }}

      - name: Trigger App Gateway Workflow
        uses: ./.github/workflows/appgw-tewheke-workflow.yaml
        with:
          environment: ${{ github.event.inputs.environment }}

      - name: Trigger Private DNS Zones Workflow
        uses: ./.github/workflows/privatednszones-tewheke-workflow.yaml
        with:
          environment: ${{ github.event.inputs.environment }}