name: "infra-rg-networking-tewheke-workflow"

on:
  workflow_call:
    inputs:
      environment:
        description: "The target environment for deployment (e.g., dev, test, prod)"
        required: true
        type: string
  workflow_dispatch:
    inputs:
      environment:
        description: "The target environment for deployment (e.g., dev, test, prod)"
        required: true
        type: string

env:
  root_directory: "rg-networking-tewheke/Infrastructure"
  sub_directory: "rg-networking-tewheke/Infrastructure/ResourceGroup"
  terraform_state_filename: "rg-networking-tewheke.tfstate"

jobs:
  # Dev Environment
  dev:
    if: ${{ inputs.environment == 'dev' }}
    permissions:
      id-token: write # Required for OIDC authentication
      contents: read # To access repository files if needed
    uses: MitchAbelDevOps/DevOps/.github/workflows/deploy-resource.yaml@main
    with:
      environment: "dev"
      root_directory: ${{ env.root_directory }}
      sub_directory: ${{ env.sub_directory }}
      terraform_state_filename: ${{ env.terraform_state_filename }}
    secrets: inherit

  # # Test Environment
  # test:
  #   if: ${{ inputs.environment == 'test' }}
  #   permissions:
  #     id-token: write # Required for OIDC authentication
  #     contents: read  # To access repository files if needed
  #   uses: MitchAbelDevOps/DevOps/.github/workflows/deploy-resource.yaml@main
  #   with:
  #     environment: 'test'
  #     root_directory: ${{ env.root_directory }}
  #     sub_directory: ${{ env.sub_directory }}
  #     terraform_state_filename: ${{ env.terraform_state_filename }}

  # # Staging Environment
  # staging:
  #   if: ${{ inputs.environment == 'stg' }}
  #   permissions:
  #     id-token: write # Required for OIDC authentication
  #     contents: read  # To access repository files if needed
  #   uses: MitchAbelDevOps/DevOps/.github/workflows/deploy-resource.yaml@main
  #   with:
  #     environment: 'staging'
  #     root_directory: ${{ env.root_directory }}
  #     sub_directory: ${{ env.sub_directory }}
  #     terraform_state_filename: ${{ env.terraform_state_filename }}

  # # UAT Environment
  # uat:
  #   if: ${{ inputs.environment == 'uat' }}
  #   permissions:
  #     id-token: write # Required for OIDC authentication
  #     contents: read  # To access repository files if needed
  #   uses: MitchAbelDevOps/DevOps/.github/workflows/deploy-resource.yaml@main
  #   with:
  #     environment: 'uat'
  #     root_directory: ${{ env.root_directory }}
  #     sub_directory: ${{ env.sub_directory }}
  #     terraform_state_filename: ${{ env.terraform_state_filename }}
  # # Prod Environment
  # prod:
  #   if: ${{ inputs.environment == 'prod' }}
  #   permissions:
  #     id-token: write # Required for OIDC authentication
  #     contents: read  # To access repository files if needed
  #   uses: MitchAbelDevOps/DevOps/.github/workflows/deploy-resource.yaml@main
  #   with:
  #     environment: 'prod'
  #     root_directory: ${{ env.root_directory }}
  #     sub_directory: ${{ env.sub_directory }}
  #     terraform_state_filename: ${{ env.terraform_state_filename }}
