name: 'vnet-tewheke-workflow'

on:
  workflow_dispatch: # Trigger manually via GitHub Actions interface

env:
  AZURE_CORE_LOG_LEVEL: DEBUG

jobs:
  dev:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: dev

    permissions:
      id-token: write # Required for OIDC authentication
      contents: read  # To access repository files if needed

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v4

    # Login to Azure using OIDC
    - name: Azure Login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    # Test script
    - name: Azure CLI script
      uses: azure/cli@v2
      with:
        azcliversion: latest
        inlineScript: |
          az account show
          az storage -h

    # Retrieve Storage account key, change to MSI?
    - name: Get Terraform Storage Account Key
      id: get-key
      uses: azure/cli@v2
      with:
        inlineScript: |
          key=az storage account keys list -g "rg-integrationmanagement-aue" -n "saterraformstateauedev" --query [0].value -o tsv
    #      echo "::set-output name=storage_account_key::$key"

    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
    - name: Install Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: '1.5.0'

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      run: |
        terraform init \
          -backend-config="storage_account_name=saterraformstateauedev" \
          -backend-config="container_name=integration-terraform-state" \
          -backend-config="key=vnet-tewheke.tfstate" \
          -backend-config="access_key=${{ steps.get-key.outputs.storage_account_key }}"
      working-directory: 'rg-networking-tewheke/Infrastructure/Virtual Network'

      

    # Checks that all Terraform configuration files adhere to a canonical format
    - name: Terraform Format
      run: terraform fmt -check

    # # Generates an execution plan for Terraform
    # - name: Terraform Plan
    #   run: terraform plan -input=false

    #   # On push to "main", build or change infrastructure according to Terraform configuration files
    #   # Note: It is recommended to set up a required "strict" status check in your repository for "Terraform Cloud". See the documentation on "strict" required status checks for more information: https://help.github.com/en/github/administering-a-repository/types-of-required-status-checks
    # - name: Terraform Apply
    #   run: terraform apply -auto-approve -input=false
